[2025-06-13T22:59:54.734+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_projeto.load_dw manual__2025-06-13T22:59:38.638180+00:00 [queued]>
[2025-06-13T22:59:54.745+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_projeto.load_dw manual__2025-06-13T22:59:38.638180+00:00 [queued]>
[2025-06-13T22:59:54.745+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-13T22:59:54.760+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_dw> on 2025-06-13 22:59:38.638180+00:00
[2025-06-13T22:59:54.764+0000] {standard_task_runner.py:60} INFO - Started process 256 to run task
[2025-06-13T22:59:54.767+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_projeto', 'load_dw', 'manual__2025-06-13T22:59:38.638180+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpemrm0_u_']
[2025-06-13T22:59:54.770+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask load_dw
[2025-06-13T22:59:54.843+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_projeto.load_dw manual__2025-06-13T22:59:38.638180+00:00 [running]> on host a984848cc8d0
[2025-06-13T22:59:54.964+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kayo' AIRFLOW_CTX_DAG_ID='etl_projeto' AIRFLOW_CTX_TASK_ID='load_dw' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T22:59:38.638180+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-13T22:59:38.638180+00:00'
[2025-06-13T22:59:55.834+0000] {logging_mixin.py:188} INFO - Carga no DW finalizada!
[2025-06-13T22:59:55.835+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-13T22:59:55.849+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_projeto, task_id=load_dw, execution_date=20250613T225938, start_date=20250613T225954, end_date=20250613T225955
[2025-06-13T22:59:55.904+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-13T22:59:55.928+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
