[2025-06-14T00:00:15.271+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_projeto.load_dw scheduled__2025-06-13T00:00:00+00:00 [queued]>
[2025-06-14T00:00:15.281+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_projeto.load_dw scheduled__2025-06-13T00:00:00+00:00 [queued]>
[2025-06-14T00:00:15.282+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-06-14T00:00:15.302+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_dw> on 2025-06-13 00:00:00+00:00
[2025-06-14T00:00:15.308+0000] {standard_task_runner.py:60} INFO - Started process 813 to run task
[2025-06-14T00:00:15.312+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_projeto', 'load_dw', 'scheduled__2025-06-13T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp1zmoax71']
[2025-06-14T00:00:15.315+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask load_dw
[2025-06-14T00:00:15.391+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_projeto.load_dw scheduled__2025-06-13T00:00:00+00:00 [running]> on host a984848cc8d0
[2025-06-14T00:00:15.495+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dados@maxinutri.com.br' AIRFLOW_CTX_DAG_OWNER='kayo' AIRFLOW_CTX_DAG_ID='etl_projeto' AIRFLOW_CTX_TASK_ID='load_dw' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T00:00:00+00:00'
[2025-06-14T00:00:16.319+0000] {logging_mixin.py:188} INFO - Carga no DW finalizada!
[2025-06-14T00:00:16.320+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-14T00:00:16.335+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_projeto, task_id=load_dw, execution_date=20250613T000000, start_date=20250614T000015, end_date=20250614T000016
[2025-06-14T00:00:16.368+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-14T00:00:16.391+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
